import archiver from "archiver";
import { PassThrough } from "stream";
import { GroqError } from "./groq.js";
import { listRunFilesRecursive, runManifestPath } from "./runFiles.js";
import { storage } from "./storage.js";

function bufferFromStream(stream) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    stream.on("data", (chunk) => chunks.push(chunk));
    stream.on("end", () => resolve(Buffer.concat(chunks)));
    stream.on("error", reject);
  });
}

export async function createRunZipBuffer(runId) {
  const files = await listRunFilesRecursive(runId);
  if (!files.length) throw new GroqError("No files to zip");

  const archive = archiver("zip", { zlib: { level: 9 } });
  const passthrough = new PassThrough();
  archive.pipe(passthrough);

  for (const file of files) {
    archive.append(file.content, { name: file.path });
  }

  try {
    const manifest = await storage.readText(runManifestPath(runId));
    archive.append(manifest, { name: "open-ide-manifest.json" });
  } catch {
    // optional
  }

  archive.append(
    [
      "# Generated by Open IDE",
      "",
      "## Run locally",
      "```bash",
      "npm init -y",
      "npm install express cors body-parser",
      "node server.js",
      "```",
      "",
    ].join("\n"),
    { name: "README.md" }
  );

  await archive.finalize();
  return bufferFromStream(passthrough);
}
